version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8124:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse/

  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:v8.4.3
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim-dev"
      mongo_atnaUrl: "mongodb://mongo-db/openhim-dev"
      NODE_ENV: "production"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:poc-microfrontend
    restart: unless-stopped
    ports:
      - "9000:80"

volumes:
  mongo-data:
  zookeeper_data:
  kafka_data:
  clickhouse_data:
