name: Scan latest docker image

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  scan-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t jembi/kafka-mapper-consumer:${{ github.sha }} ./apps/kafka-mapper-consumer && \
          docker build -t jembi/kafka-mapper-consumer-ui:${{ github.sha }} ./apps/kafka-mapper-microfrontend

      - name: Run trivy vulnerability scanner for the Kafka Mapper consumer image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: jembi/kafka-mapper-consumer:${{ github.sha }}
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

      - name: Run trivy vulnerability scanner for the Kafka Mapper consumer UI image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: jembi/kafka-mapper-consumer-ui:${{ github.sha }}
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
